"""Generate CI pipeline files from bam.yaml configuration.

Supports GitHub Actions and GitLab CI.  The generated pipeline is a
"thin wrapper": each bam task becomes one CI job that calls ``bam <task>``.
Dependencies are wired through the CI ``needs:``/``needs`` mechanism so the CI
runner can still parallelize at the job level, while bam itself handles
caching and per-task progress reporting inside each job.
"""

from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from bam_tool.config.schema import BamConfig, CiConfig, TaskConfig


# ci-job names may only contain alphanumerics, hyphens and underscores
def _job_name(task_name: str) -> str:
    return task_name.replace(" ", "-")


# ---------------------------------------------------------------------------
# GitHub Actions
# ---------------------------------------------------------------------------

def _github_setup_steps(ci: CiConfig) -> list[dict[str, Any]]:
    """Return the common boilerplate steps for every job."""
    steps: list[dict[str, Any]] = [{"uses": "actions/checkout@v4"}]
    if ci.python_version:
        steps.append({
            "uses": "actions/setup-python@v5",
            "with": {"python-version": ci.python_version},
        })
    steps.append({
        "uses": "astral-sh/setup-uv@v5",
        "with": {"enable-cache": "true"},
    })
    steps.append({
        "name": "Install bam",
        "run": "uv tool install bam-tool",
    })
    return steps


def _github_job(
    task_name: str,
    depends_on: list[str],
    ci: CiConfig,
) -> dict[str, Any]:
    job: dict[str, Any] = {
        "runs-on": ci.runner,
    }
    if depends_on:
        job["needs"] = [_job_name(d) for d in depends_on]
    job["steps"] = [
        *_github_setup_steps(ci),
        {
            "name": f"Run {task_name}",
            "run": f"bam {task_name}",
        },
    ]
    return job


def _generate_github_actions(config: BamConfig) -> str:
    """Render a GitHub Actions workflow YAML string."""
    ci = config.ci
    assert ci is not None  # caller guarantees this

    workflow: dict[str, Any] = {
        "name": "CI",
        "on": ci.triggers,
    }
    if ci.env:
        workflow["env"] = ci.env

    jobs: dict[str, Any] = {}
    for task_name, task in config.tasks.items():
        jobs[_job_name(task_name)] = _github_job(task_name, task.depends_on, ci)

    workflow["jobs"] = jobs

    return yaml.dump(workflow, default_flow_style=False, sort_keys=False, allow_unicode=True)


# ---------------------------------------------------------------------------
# GitLab CI
# ---------------------------------------------------------------------------

_GITLAB_CI_HEADER = """\
# Generated by bam ci generate — do not edit manually.
#
# These are reusable job *templates*. Extend them to create real jobs by adding
# your own image, before_script, and any other overrides. Example:
#
#   lint:
#     extends: .lint             # <-- template name
#     image: python:3.13         # <-- your image
#     before_script:             # <-- your setup
#       - pip install uv
#       - uv sync --dev --frozen
#
# When stages are defined, concrete jobs must declare the same stage as their
# template (GitLab does not inherit stage through extends).
#
# Reference: https://docs.gitlab.com/ee/ci/yaml/#extends
"""

_SECTION_WIDTH = 79


class _IndentedDumper(yaml.Dumper):
    """Dumper that indents list items under their parent key."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:  # type: ignore[override]
        return super().increase_indent(flow=flow, indentless=False)


def _yaml_dump(data: dict[str, Any]) -> str:
    return yaml.dump(
        data,
        Dumper=_IndentedDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )


def _standard_rules() -> list[dict[str, str]]:
    return [
        {"if": '$CI_PIPELINE_SOURCE == "merge_request_event"'},
        {"if": "$CI_COMMIT_BRANCH"},
        {"if": "$CI_COMMIT_TAG"},
    ]


def _section_comment(title: str) -> str:
    bar = "\u2500" * max(1, _SECTION_WIDTH - 6 - len(title))
    return f"# \u2500\u2500\u2500 {title} {bar}"


def _render_gitlab_template(job_name: str, body: dict[str, Any]) -> str:
    """Render `.job-name:\n  key: value\n...` with the leading dot unquoted."""
    body_yaml = _yaml_dump(body)
    return f".{job_name}:\n{textwrap.indent(body_yaml, '  ')}"


def _gitlab_job_template(task_name: str, task: TaskConfig) -> dict[str, Any]:
    """Build the body dict for a hidden GitLab CI job template."""
    job: dict[str, Any] = {}
    if task.stage:
        job["stage"] = task.stage
    if task.depends_on:
        job["needs"] = [_job_name(d) for d in task.depends_on]
    job["script"] = [f"bam {task_name}"]
    if task.outputs:
        job["artifacts"] = {
            "paths": task.outputs,
            "expire_in": "7 days",
        }
    job["rules"] = _standard_rules()
    return job


def _generate_gitlab_ci(config: BamConfig) -> str:
    """Render a GitLab CI YAML string of hidden job templates."""
    ci = config.ci
    assert ci is not None

    parts: list[str] = [_GITLAB_CI_HEADER]

    # Collect stages in declaration order (first-seen wins).
    stages: list[str] = []
    seen_stages: set[str] = set()
    for task in config.tasks.values():
        if task.stage and task.stage not in seen_stages:
            stages.append(task.stage)
            seen_stages.add(task.stage)

    top: dict[str, Any] = {}
    if stages:
        top["stages"] = stages
    if ci.env:
        top["variables"] = ci.env
    if top:
        parts.append(_yaml_dump(top))

    # Emit templates grouped by stage; tasks without a stage appear last.
    by_stage: dict[str | None, list[tuple[str, TaskConfig]]] = {}
    for task_name, task in config.tasks.items():
        by_stage.setdefault(task.stage, []).append((task_name, task))

    for stage in [*stages, None]:
        if stage not in by_stage:
            continue
        section_title = stage if stage else "other"
        parts.append(_section_comment(section_title))
        templates = [
            _render_gitlab_template(_job_name(t), _gitlab_job_template(t, cfg))
            for t, cfg in by_stage[stage]
        ]
        parts.append("\n".join(templates))

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_pipeline(config: BamConfig) -> tuple[str, str]:
    """Generate a CI pipeline file from a BamConfig.

    Args:
        config: Loaded bam configuration.  Must have a ``ci`` section.

    Returns:
        A tuple of ``(filename, content)`` where *filename* is the canonical
        output path (e.g. ``.github/workflows/ci.yml``) and *content* is the
        full YAML text to write.

    Raises:
        ValueError: If ``config.ci`` is ``None`` or the provider is unknown.
    """
    if config.ci is None:
        raise ValueError(
            "No 'ci:' section found in bam.yaml. "
            "Add a 'ci:' block with at least 'provider: github-actions' to use this command."
        )

    match config.ci.provider:
        case "github-actions":
            return ".github/workflows/ci.yml", _generate_github_actions(config)
        case "gitlab-ci":
            return ".gitlab-ci.yml", _generate_gitlab_ci(config)
        case _:
            raise ValueError(f"Unknown CI provider: {config.ci.provider!r}")
